### ISSUE TITLE
Finish NBT implementation

### ISSUE THREAD

**Issue by MyzelYam** [CleanstoneMC/Cleanstone#27]

**Comment by momothereal** [comment]
Is storing the original binary data for NBT tags a design choice? It seems unnecessary to keep this in memory:
https://github.com/CleanstoneMC/Cleanstone/blob/e1054b3fc5fc0e3ec664b28f9d883ef4319798b0/src/main/java/rocks/cleanstone/data/vanilla/nbt/type/AbstractTag.java#L9-L11

Parsing tags "when necessary" (in the `get` method) can also be expensive for bigger objects like Lists and Compounds. Wouldn't it be preferable to do something like:

```java
byte[] rawData = ...;
CompoudTag tag = new CompoundTag(); // creates empty Map<String, AbstractTag>
tag.loadData(rawData); // parse the data and fill the map
// rawData gets GC'd at end of scope
```
