### ISSUE TITLE
New Chunk (BlockData) storage format - Feedback is appreciated

### ISSUE THREAD

**Issue by MyzelYam** [CleanstoneMC/Cleanstone#38]
CleanstoneMC concept: FlexibleBlockStateMapping & FlexibleBlockDataCodec

BLOCKSTATE SERIALIZATION
- Data about the BlockState is written to a ByteBuf in a linear fashion

blockType: VarInt - from extensible enum with hardcoded indexes ordered by expected usage frequency
-> BlockTypes can be removed without affecting other BlockType indexes
-> Infinite new BlockTypes can be appended at the end due to VarInt's nature

property:
|  propertyType: VarInt - property type
|  propertySize: VarInt (byte?)- following property size in bytes
|  serializedProperty: byte[]
  
blockState: BlockType >> isPropertiesEndBit=false >> property >> isPropertiesEndBit=false >> ... >> property >> isPropertiesEndBit=true

CHUNK SERIALIZATION
- Chunk is divided into 16^2 vertical columns
- BlockStates are written into the ChunkData column by column from bottom to top

blockStateAmount: VarInt - number of successive block states of same type

chunk: blockState >> blockStateAmount >> isColumnEndBit=false >> ... >> blockState >> blockStateAmount >> isColumnEndBit=true >> (next column)

SUMMARY

Notes:
- Light will be saved as a property of the AIR (and transparent?) BlockTypes
- Biomes are saved elsewhere (different LevelDB key)

Pros:
- Infinite new BlockState property types can be added later on with linear&logarithmic BlockState size increase; missing blockState properties during deserialization get a default value
- BlockState property types can be removed later on; removed property types will simply be ignored during deserialization
- Infinite new BlockTypes can be added/removed later on with logarithmic size increase
- There is no chunk height limit

Cons:
- Cant write to the chunk without reading it in its entirety, though you could divide a chunk into vertical sub-chunks
- Length and type fields have to be saved
- VarInts dont come without speed and storage overhead

**Comment by fionera** [comment]
Since we need to map the interger id to smth the mappings have I would suggest to add a mapping from the minecraft string names to the used integers. This makes it easy to extend and does not have much overhead.
