### ISSUE TITLE
Will plugin support be there any time soon?

### ISSUE THREAD

**Issue by ShadowAriaa** [CleanstoneMC/Cleanstone#59]
Hi there! I'd like to know whether or not this project will support plugins any time soon. I'm a maintainer of [Impulse](https://github.com/impulsecl/impulse) and I'm currently implementing plugin support for all the servers I can find. Impulse relies on plugins for reporting back to a swarm instance (basically a component which keeps track of everything), that the server has been started successfully. 

An answer would be much appreciated.
Sincerely, ShadowAria.

**Comment by fionera** [comment]
Hi ShadowAria,
we currently dont have any eta when there will be a Plugin System. If you want I can ping you when we have one :)

**Comment by ShadowAriaa** [comment]
Sure! Thank you very much.
