### ISSUE TITLE
'demo.cleanstone.rocks' test server offline/not reachable

### ISSUE THREAD

**Issue by 4zuree** [CleanstoneMC/Cleanstone#63]
![lzoeh](https://user-images.githubusercontent.com/50335928/60265712-ab93c900-98e6-11e9-95f2-0522274939d7.gif)
(I actually type way faster, but the mp4 to gif conversion removed a lot of frames, in case you're wondering lolz)

(https://streamable.com/lzoeh)

**Comment by fionera** [comment]
Yeah the server is currently offline

**Comment by 4zuree** [comment]
Any ETA until the server will be up and running?

**Comment by fionera** [comment]
It should be back online now... The Webadmin is available too

**Comment by 4zuree** [comment]
Just tried that. Still offline.

**Comment by fionera** [comment]
Try with port 25566 also I just changed the DNS...

**Comment by 4zuree** [comment]
`demo.cleanstone.rocks:25566` not working. Will try again in a hour.

**Comment by fionera** [comment]
ah found it... there was a port forwarding error... should work now

**Comment by 4zuree** [comment]
Server is up and reachable again. Thank you very much!
