### ISSUE TITLE
Port 8080 not changeable.

### ISSUE THREAD

**Issue by josephworks** [CleanstoneMC/Cleanstone#66]
`***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.`

my config:
`spring:

  boot:

    admin:

      client:

        url: http://localhost:8070

        instance.name: "Cleanstone Main"

      ui:

        title: "Cleanstone Admin"

  profiles:

    active: mainServer

  thymeleaf:

    check-template-location: false

`
**It appears that port 8080 is not able to be changed.**

**Comment by fionera** [comment]
You also have to define the following setting: `spring.boot.admin.ui.public-url: http://localhost:8181`
